### ISSUE TITLE
@get /tapahtumat/tulevat muokkaus

### ISSUE THREAD

**Issue by bfm471** [vilp91/Lipunmyyntijarjestelma#102]

**Comment by bfm471** [comment]
Tähän voisi sopia esim. request parameter, jolla voisi antaa päivämäärän, minä jälkeisiä tapahtumia haetaan.

**Comment by bfm471** [comment]
Tai ehkä parametrissä voisi päättää hakeeko avoimia vai sulkeutuneita tapahtumia...?

**Comment by Romaalie** [comment]
Mitä vikaa siis on siinä, että etsitään LocalDateTime tanaan = LocalDateTime.now().with(LocalTime.MAX);?
Eikö se näytä tulevat tapahtumat? :D

Ehkä voisi olla oma metodinsa sitten jos halutaan etsiä vaikka /tapahtumat/?avoin=true tai /tapahtumat/?date={yyyy-mm-dd} tmv

**Comment by bfm471** [comment]
Markku oli kovasti sitä mieltä, että tämmöinen end pointti ei vetele. Ja että se tulisi muuttaa rest API käytännön  mukaiseksi. 
Ja kun me  rest apia tässä opetellaan tekemään, niin noudattaisin mielelläni Markun ohjetta 😂

Parametreja vois olla esmes kaks, alku ja loppupäivä. Jos antaa molemmat, haetaan tapahtumia niiden väliltä. Jos antaa vain ekan, haetaan tapahtumat siitä alkaen. Jos antaa vain tokan, haetaan tapahtumat siihen asti.  Eli client voisi käyttää samaa endpointtia hyvinkin monimuotoisesti. 
Tämä siis esimerkkinä vaihtoehdoista.

**Comment by bfm471** [comment]
jatkan vielä tuumailua...
tämänhän ei itseasiassa tarvitse olla oma erillinen endpoint, vaan me voidaan halutessamme laajentaa @get /tapahtumat käsittämään myös nuo yllä mainitut vaihtoehdot. Ja tosiaan jos parametreja ei anna pyyntöön ollenkaan, niin haetaan kaikki olemassa olevat tapahtumat.

**Comment by Romaalie** [comment]
Mikä siis oli se ongelma tuon REST APIn kanssa? Miten Markku sanoi, että se rikkoo niitä käytäntöjä? Oppimisen kannalta kiinnostaa.

**Comment by bfm471** [comment]
Referoin sut Moodlen REST API -välilehdelle, matskuun Rest-api:n suunnittelu.
Siellä jutellaan tämmöisiä:


![Image](https://github.com/vilp91/Lipunmyyntijarjestelma/assets/131486512/037c8af3-40d2-44f4-bd1d-4e9018980c71)
