### ISSUE TITLE
Error messaget JSON-muotoisiksi

### ISSUE THREAD

**Issue by bfm471** [vilp91/Lipunmyyntijarjestelma#134]

**Comment by bfm471** [comment]
Tällä hetkellä virheviestit ovat pelkkä tekstiä. Ne pitäisi saada JSON-muotoon

**Comment by Romaalie** [comment]
Suurin osa virheviesteistä muutettu palauttamaan JSONIA hyödyntämällä ResponseStatusExceptionia.
Metodeista joita ei saatu korjattua on tehty uudet issuet.
