### ISSUE TITLE
@post /tapahtumanlipputyypit Nyt on mahdollista luoda useampi tapahtumanlipputyyppi samalla lipputyyppiId:llä

### ISSUE THREAD

**Issue by Romaalie** [vilp91/Lipunmyyntijarjestelma#150]
Metodissa on aloitettu työstämään tarkistusta tälle, mutta ei ehtinyt loppuun tässä sprintissä.

**Comment by bfm471** [comment]
O-ou, nyt taidetaan blokata lipputyypin käyttö kaikissa muissakin tapahtumissa.
Eli jos tapahtuma 1 on käyttänyt lipputyyppi 1:stä, niin mikään muu tapahtuma ei voi luoda lipputyppi ykkösestä omaa tapahtumanlipputyyppiään.

Tsekkaillaan kun ehditään.

**Comment by Romaalie** [comment]
Korjattu. Uudelleen. Kiitos kun huomasit ongelman!
Ehdin testailemaan vain nopeasti läpi postmanilla, että nyt pitäisi toimia ja ainakin suurin osa error vastauksista tuli myös oikein. Kattavampaa testailua en nyt ehtinyt toteuttamaan eli ilmoita vaan jos ei vieläkään pelitä ihan niin kuin pitäisi!
