### ISSUE TITLE
Lippu entityn muokkaaminen uusien vaatimusten mukaiseksi

### ISSUE THREAD

**Issue by Romaalie** [vilp91/Lipunmyyntijarjestelma#173]
Lippu entityyn tarvitaan uusia attribuutteja:
"Käytetty"; voiko olla boolean? Moodlen esimerkissä on ilmeisesti kylläkin DateTime.
"Koodi"; eli yksilöllinen koodi lipulle. Jonkinlainen satunnaisgeneraattori? Uniikki.

Tänne voi kommentoida lisää ajatuksia.

**Comment by bfm471** [comment]
Tein käytetty attribuutin DateTimena. Käyttämättömän lipun attribuutin arvo on null.

Koodi -> lippunumero (voidaan muuttaa.. on vähän kökkö)
Mulla meni täydellisesti kuppi nurin tän kanssa, joten päädyin tekemään sen UUID:na joka on helposti ja varmasti aina uniikki. Toivottavasti toimii loppuun saakka :)
