### ISSUE TITLE
RestLippuController PATCH tai PUT /liput/{id}

### ISSUE THREAD

**Issue by Romaalie** [vilp91/Lipunmyyntijarjestelma#175]
Metodi, jolla merkitään lippu käytetyksi.

MUISTA API DOKUMENTAATION PÄIVITYS.

CORS tuen toteuttaminen.

**Comment by bfm471** [comment]
Tuumailin tätä, että lienee parempi tehdä se patchina. Silloin lipuntarkastaja ei vahingossa pääse muokkaamaan lipusta mitään muuta tietoa.

**Comment by bfm471** [comment]
Toteutettu patchina
