### ISSUE TITLE
Front end client

### ISSUE THREAD

**Issue by Romaalie** [vilp91/Lipunmyyntijarjestelma#176]
Pienimuotoinen front end clientti jolla voi:

- hakea lippukoodin perusteella lipun tiedot
- merkitä lipun käytetyksi

Mihin client tehdään? Nykyiseen projektiimme? Omaan haaraansa? Julkaistaanko GitHubPagesissa?

**Comment by bfm471** [comment]
Client on nyt omassa haarassa, mutta toimii vain omalla testidatalla.
Tehdään pidemmälle, kun on api jota vasten voi testata.

**Comment by bfm471** [comment]
Toimii tällä hetkellä meidän omaa apia vasten. Muokkaillaan KOVASille sopivaksi sitten kun he on valmiita.

**Comment by bfm471** [comment]
Päätettiin jättää tekemättä KOVASin bäckiin, kun kaikki endpointit ei heillä toimi.
