### ISSUE TITLE
CORS tuki globaalit asetukset

### ISSUE THREAD

**Issue by bfm471** [vilp91/Lipunmyyntijarjestelma#184]

**Comment by bfm471** [comment]
Noh, se toimii jotenkin...

**Comment by Romaalie** [comment]
Toimii, mutta CorsConfigurationSource:ssa on nyt configuration.setAllowCredentials(true) kommentoitu pois.
Voisi vielä selvittää onko ongelma clientin päässä preflightissa lähtevissä tiedoissa (credentials) vai missä, jotta tuo saataisiin takaisin.
Ei se kai mikään ehdottoman pakollinen oo, mutta..
