### ISSUE TITLE
Dokumentaation luku Tietokanta

### ISSUE THREAD

**Issue by Romaalie** [vilp91/Lipunmyyntijarjestelma#19]
Tämä pitänee jakaa pienempiin osiin?

**Comment by bfm471** [comment]
Mie hoidan

**Comment by bfm471** [comment]
Valmis ja viety deviin.
Jo päädytään tekemään jotain ehdotetuista muutoksista, niin nekin on paikallisesti valmiina ja vien sitten tarvittaessa deviin.
