### ISSUE TITLE
Lisää käyttäjä -metodin tarkistus

### ISSUE THREAD

**Issue by bfm471** [vilp91/Lipunmyyntijarjestelma#191]
@post /kayttajat 
Nyt http-pyynnön pitää sisältää sekä rooliId että roolin nimi. Luulen että pelkkä Id riittäisi.
Tämän osalta pitäisi päivittää myös dokumentaatio.

Dokumentaation mukaan onnistuneen pyynnön response sisältää myös käyttäjän salasanan. Onkohan se ihan turvallista?
Entityssä oli pois kommentoidut JsonIgnoret salasanassa, roolissa ja käyttäjänimessä. Nappasin ne takaisin toimintaan, kun oletin että olivat jääneet vahingossa.

**Comment by Romaalie** [comment]
Kävin katsomassa niin tällä hetkellä ei tämä metodi näytä toimivan ollenkaan vaan palauttaa virhettä kayttaja.salasanan ja kayttaja.kayttajanimen puuttumisesta.. Tutkin ehkä lisää jos on aikaa, en lupaa mitään.

**Comment by bfm471** [comment]
Toi virhe oli tosiaan kiinni niistä JsonIgnoreista salasanassa ja käyttäjänimessä. Kun ne kommentoi pois, niin post toimii normaalisti.
Vielä olisi ratkaisematta ensimmäinen osa alkuperäistä ongelmaa:

> Nyt http-pyynnön pitää sisältää sekä rooliId että roolin nimi. Luulen että pelkkä Id riittäisi.
> Tämän osalta pitäisi päivittää myös dokumentaatio.

**Comment by Romaalie** [comment]
Metodi toimii nyt myös pelkällä rooliId:llä.
Hyväksyy myös vanhan tavan laittaa koko Rooli objekti pyyntöön mukaan. 
Metodi palauttaa response bodyssa käyttäjän tiedot ilman salasanaa (=null).
Dokumentaatio päivitetty.
