### ISSUE TITLE
MyyntitapahtumaDTO muokkaus

### ISSUE THREAD

**Issue by Romaalie** [vilp91/Lipunmyyntijarjestelma#196]

**Comment by Romaalie** [comment]
MyyntitapahtumaDTO palauttaa tällä hetkellä kaikki käyttäjän tiedot. Emme halua palauttaa jokaisessa myyntitapahtumassa mm. käyttäjän salasanaa ja käyttäjätunnusta. Muokataan DTO palauttamaan vain myyntitapahtuman kannalta olennaiset tiedot.

**Comment by Tuutej** [comment]
Myyntitapahtuma palauttaa tällä hetkellä tämän verran tietoa käyttäjästä:
```
"kayttaja": {
            "kayttajaId": 29,
            "etunimi": "Teppo",
            "sukunimi": "Testaaja",
            "puhnro": null,
            "katuosoite": null
        }
```

**Comment by bfm471** [comment]
Live-versio palauttaa tosiaan vain nuo yllä olevassa kuvassa näkyvät tiedot, eli mitään salaisuuksia ei paljasteta myyntitapahtuman luomisen yhteydessä.
Kehitysympäristössä käyttäjästä palautuu kaikki tieto, salasanaa ja käyttäjänimeä myöten, mutta se lienee hyödyllistä.

**Comment by bfm471** [comment]
Otettiin issue uuteen käsittelyyn, kun kävi ilmi, että myös live versio palauttaa sittenkin käyttäjän salasanan ja käyttäjänimen. 
Uudessa ratkaisussa MyyntitapahtumaDto muokattiin näyttämään käyttäjästä pelkästään kayttajaId.
