### ISSUE TITLE
Lipunmyyjänä haluan, että myyntijärjestelmä on yksinkertainen, jotta se on helppo kouluttaa uusille työntekijöille

### ISSUE THREAD

**Issue by Romaalie** [vilp91/Lipunmyyntijarjestelma#24]
Laatuvaatimus. Mitattavuuden määrittely?

**Comment by Romaalie** [comment]
Me ei tehdä frontin puolen clientia eli tämä turha vaatimus meille? Poistetaanko?

**Comment by bfm471** [comment]
Eikös me vähän jotain fronttiakin kehitellä


![Image](https://github.com/vilp91/Lipunmyyntijarjestelma/assets/131486512/2e7a0ea2-fa33-4eb8-ab41-777d15312bbf)
