### ISSUE TITLE
Tapahtumien hallinnoijana haluan pystyä määrittelemään eri käyttäjäryhmille eri hintaisia lippuja, jotta voimme kohdentaa markkinointia

### ISSUE THREAD

**Issue by Romaalie** [vilp91/Lipunmyyntijarjestelma#25]

**Comment by Romaalie** [comment]
Eikös tämä ole jo jossain määrin ainakin toteutettu?

**Comment by bfm471** [comment]
Samaa mieltä. Tapahtumille pystyy luomaan tapahtumanlipputyyppejä ja hinnoittelemaan ne tapahtumakohtaisesti.
Pistän sulkien.
