### ISSUE TITLE
Markkinointijohtajana haluan pystyä tulostamaan myyntiraportteja, jotta voin käyttää tätä dataa tulevien tapahtumien suunnitteluun

### ISSUE THREAD

**Issue by Romaalie** [vilp91/Lipunmyyntijarjestelma#26]

**Comment by Romaalie** [comment]
Onko tämä jo käytännössä mahdollista? Poistetaan?

**Comment by bfm471** [comment]
Myyntiraportti on käytännössä yhteen tapahtumaan liittyvien myyntitapahtumien tiedot.
Meillä on kyllä endpointti josta voi hakea _kaikkien_ tapahtumien myyntitapahtumat, mutta ei yhden tietyn tapahtuman myyntitapahtumia.
Lisään tästä jonoon uuden tehtävän.

**Comment by bfm471** [comment]
Enpäs lisääkään, kun moinen tehtävä on jo olemassa. Se on toi [#94](https://github.com/vilp91/Lipunmyyntijarjestelma/issues/94), joka on tarkistettavat-sarakkeessa

**Comment by bfm471** [comment]
Nyt on https://github.com/vilp91/Lipunmyyntijarjestelma/issues/94 toteutettu, niin suljetaan tämä issue myös.
