### ISSUE TITLE
Järjestelmän tilaajana haluan pystyä myymään lippuja järjestämiini tapahtumiin

### ISSUE THREAD

**Issue by Romaalie** [vilp91/Lipunmyyntijarjestelma#28]

**Comment by bfm471** [comment]
Onko järjestelmän tilaaja meidän skenaariossa lippujen välittäjä (samoin kuin esimerkiksi Lippu.fj) vai tapahtumanjärjestäjä?

**Comment by bfm471** [comment]
Lippujen myyminen tapahtumiin on toteutettu, joten suljetaan tämä.
