### ISSUE TITLE
Cascade sääntöjen korjaaminen

### ISSUE THREAD

**Issue by Romaalie** [vilp91/Lipunmyyntijarjestelma#76]
Tällä hetkellä kun poistaa esim. lipputyypin niin samalla poistuu kaikki siihen liittyvät liput. Myös myyntitapahtumien sisältä, nollaten myyntitapahtumien summan samalla.

**Comment by bfm471** [comment]
Toteutin nyt tällaisella lopputulemalla:

Kaikki delete-metodit merkitsevät poistettavan tietueen poistetuksi (poistettu-attribuutti: true). Näin ollen mitään ei varsinaisesti poisteta, mikä tarkoittaa, että ajan kuluessa tietokannan eheys säilyy, koska viittaukset eivät menetä yhteyttään.

- Lipputyyppi
> - voi poistaa aina

- Tapahtumanlipputyyppi
>-  ei voi poistaa, jos on liitetty lippuja

- Tapahtuma
>- ei voi poistaa, jos on liitetty lippuja

- Lippu
>- voi poistaa aina

- Myyntitapahtuma
>- voi poistaa aina
>- samalla poistetaan myyntitapahtumaan sisältyvät liput   

- Käyttäjä
>- delete-metodia ei vielä toteutettu

- Rooli
>- delete-metodia ei vielä toteutettu
>-  tarvitseeko toteuttaa? Vai kuuluuko roolien kaikennäköinen hallinnointi ylläpitosopimukseen?
>-  tarvitaanko myöskään roolin luomisen mahdollistavaa  @post-metodia vai onko se turha?
