### ISSUE TITLE
Tapahtuma Entity. Tapahtuman luonnin tietojen pakollisuus: kaikki tiedot pakollisiksi?

### ISSUE THREAD

**Issue by Romaalie** [vilp91/Lipunmyyntijarjestelma#82]
Nyt voi tehdä tapahtuman pelkällä nimellä. Onko tämä kuitenkin turhan suppeaa sallia näin?

**Comment by bfm471** [comment]
Voishan ne kaikki laittaa pakollisiksi.
Se pakollisten attribuuttien vältteleminen on taas mr.Braden haamu mun aivoissa :D

**Comment by bfm471** [comment]
Kaikki muut tiedot ovat nyt pakollisia, paitsi loppu_pvm.
